# Generated by Django 2.1 on 2018-08-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingCenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='item',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='share',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
