# Generated by Django 2.1 on 2018-08-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text_field',
            new_name='text',
        ),
    ]
