# Generated by Django 2.1 on 2018-08-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='foodImages/')),
                ('description', models.TextField()),
            ],
        ),
    ]
