# Generated by Django 2.1 on 2018-08-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_employee_email'),
        ('foodOrdering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='orders',
            field=models.ManyToManyField(to='accounts.Employee'),
        ),
    ]
