# Generated by Django 2.1 on 2018-08-10 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOrdering', '0002_auto_20180810_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='orders',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
