# Generated by Django 2.1 on 2018-08-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('explanation', models.TextField()),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('approved', models.IntegerField()),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.Employee')),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reciever', to='accounts.Employee')),
            ],
        ),
    ]
