# Generated by Django 2.1 on 2018-08-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveRequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
