# Generated by Django 2.1 on 2018-08-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveRequests', '0002_auto_20180810_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='title',
        ),
    ]
